import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Registration from './Registration'

export default function Home() {



    return (

        <div className={styles.container}>
            <Head>
                <title>ACME Food Purchasing</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Registration/>


            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >

                </a>
            </footer>
        </div>
    )
}
